import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavbarDemo } from "@/components/navbar";
import Footer from "@/components/footer";
import { BackgroundBeamsWithCollision } from "@/components/ui/background-beams-with-collision";
import BotpressChat from "@/components/BotpressChat";
// TODO: Uncomment and fix the import path below if the file exists elsewhere
// import { BackgroundBeamsWithCollision } from "@/components/background-beams";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NavbarDemo />
        {/* <div className="flex flex-col items-center justify-center min-h-screen"> */}
        {children}
        {/* < BackgroundBeamsWithCollision children={undefined} /> */}
         <BotpressChat />
        <Footer />
      </body>
    </html>
  );
}
